//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certifikat
    {
        public int CertificateID { get; set; }
        public Nullable<int> OlympiadID { get; set; }
        public string Name { get; set; }
    }
}
