//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations_on_olimpiad
    {
        public int id { get; set; }
        public Nullable<int> olympiad_id { get; set; }
        public Nullable<int> student_id { get; set; }
    }
}
